services:
  chainlink_db:
    image: postgres
    container_name: chainlink_postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - postgres/db.env
  chainlink:
    image: "smartcontract/chainlink:2.8.0"
    depends_on:
      - chainlink_db
    ports:
      - "6688:6688"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ~/test-chainlink-oracle/chainlink:/chainlink/
    command: node -config /chainlink/config.toml -secrets /chainlink/secrets.toml start
